repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      exclude: ^.github/
      stages: [commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
    - id: detect-private-key
      stages: [commit]
-   repo: local
    hooks:
      - id: auto-commit-message
        name: generate commit message
        entry: .githooks/prepare-commit-msg
        language: script
        stages: [prepare-commit-msg]
        always_run: true
