name: Create Package and Deploy to TestPyPI
run-name: ${{ github.head_ref }} Create Package and Deploy to TestPyPI
on:
  workflow_dispatch:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/cognitopy/
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Publish package distributions to TestPyPI
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.9"
          repository_url: https://test.pypi.org/legacy/
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}