name: Create New Release
run-name: ${{ github.head_ref }} Create New Release
on: 
  push:
    branches:
      - release/*

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/cognitopy/
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Building Project
        run: python setup.py sdist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: guido
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
