name: Create Package and Deploy to TestPyPI
run-name: ${{ github.head_ref }} Create Package and Deploy to TestPyPI
on:
  workflow_dispatch:
jobs:
  pypi-publish-test:
    name: Upload release to PyPI test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/cognitopy/
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Publish to TestPyPI
        env:
          POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish -r test-pypi --build --username __token__ --password ${{ secrets.TEST_PYPI_API_TOKEN }}