name: Create Package and Deploy to TestPyPI
run-name: ${{ github.head_ref }} Create Package and Deploy to TestPyPI
on:
  workflow_dispatch:
jobs:
  pypi-publish-test:
    name: Upload release to PyPI test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/cognitopy/
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Building Project
        run: poetry build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}